# 加载和保存参数
定期保存训练中间结果，方便模型恢复和断点处继续训练

## [单独张量存储]
- 存储： `save`
- 加载： `load`

In [19]:
import torch
from torch import nn
from torch.nn import functional as F

In [4]:
x = torch.randn(5)
x

tensor([-1.4989, -0.7802,  1.4253,  2.3680, -0.5248])

存储单个张量

In [5]:
torch.save(x,"x-file")

In [9]:
# 单个张量
x1 = torch.load("x-file")
x1,x1 == x

(tensor([-1.4989, -0.7802,  1.4253,  2.3680, -0.5248]),
 tensor([True, True, True, True, True]))

张量列表

In [10]:
y = torch.zeros(4)
y

tensor([0., 0., 0., 0.])

In [11]:
torch.save([x,y],"xy-file")

In [14]:
x2,y2 = torch.load("xy-file")
x2,y2,x2 == x,y2 == y

(tensor([-1.4989, -0.7802,  1.4253,  2.3680, -0.5248]),
 tensor([0., 0., 0., 0.]),
 tensor([True, True, True, True, True]),
 tensor([True, True, True, True]))

张量字典

In [15]:
mydict = {"x":x,"y":y}
torch.save(mydict,"mydict")

In [18]:
mydict1 = torch.load("mydict")
mydict1

{'x': tensor([-1.4989, -0.7802,  1.4253,  2.3680, -0.5248]),
 'y': tensor([0., 0., 0., 0.])}

# 加载和保存模型参数
保存的是模型参数而不是整个模型

In [20]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20,256)
        self.output = nn.Linear(256,10)
    def forward(self,X):
        return self.output(F.relu(self.hidden(X)))

In [21]:
net = MLP()
X = torch.randn(2,20)
Y = net(X)

In [22]:
# 保存MLP的参数
torch.save(net.state_dict(),"mlp-params")

In [25]:
# 先使用代码生成模型架构，再加载参数
clone = MLP()
clone.load_state_dict(torch.load("mlp-params"))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [26]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

输出相同，说明两个模型完全一样